name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
      - Submission
  pull_request:
    branches:
      - main
      - development
      - Submission

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]  # Consider using the same version as your local dev environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for backend
        run: |
          cd ./backend
          npm install --include=dev  # Ensure dev dependencies are installed

      - name: Run backend tests
        run: |
          cd ./backend
          npm test  # Directly run tests, Jest error will be more informative

  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies for frontend
        run: |
          cd ./frontend
          npm install

 # Skip the test step, need to add test script to package.js later when i need to test the frontend.
      # - name: Run frontend tests
      #   run: |
      #     cd ./frontend
      #     npm test
